# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_DIAMANEOS_PRIVSW)			+= diamaneos_privsw.o
diamaneos_privsw-y				:= privsw.o
obj-$(CONFIG_DIAMANEOS_PRIVSW_KUNIT_TEST)	+= diamaneos_privsw_test.o
diamaneos_privsw_test-y				:= privsw_test.o
